interface Standalone_Core {
    void Standalone_Core();

    void program_compile();
    void link_flash_memory(VoidPtr p, unsigned long len);
    void define_symbol(unsigned long value, [Const] DOMString name);

    [Const] DOMString disassembly_view();

    unsigned long get_memory_size();
    VoidPtr get_memory_ptr();
    VoidPtr get_register_file_ptr();

    void run();
    void step();
};

